zappy-branch-order-history/carts/urls.py
from django.urls import path, include

from . import views

app_name='carts'

urlpatterns = [
    path('', views.view, name='cart'),
    path('<slug>', views.update_cart, name='update_cart'),
]

zappy-branch-order-history/mainapp/urls.py
from django.urls import path

from . import views

app_name='mainapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<slug>', views.detail, name='detail'),
    path('signin', views.signin, name='signin'),
    path('signup', views.signup, name='signup'),
    path('logout', views.logoutView, name='logout'),
    path('search/', views.search, name='search'),
    path('profile', views.profile, name='profile'),
]

zappy-branch-order-history/orders/urls.py
from django.urls import path

from . import views

app_name='orders'

urlpatterns = [
    path('checkout', views.checkout, name='checkout'),
    path('', views.orders, name='user_orders'),

]

zappy-branch-order-history/zappy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('carts/', include('carts.urls')),
    path('orders/', include('orders.urls')),
    path('order/', include('orders.urls')),
    path('accounts/', include('django.contrib.auth.urls'))

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zappy-branch-order-history/carts/models.py
from django.db import models

from mainapp.models import Product

# Create your models here.

class Cart(models.Model):
    # cart_products = models.ManyToManyField("CartItem", null=True, blank=True)
    # products = models.ManyToManyField(Product, null=True, blank=True)
    total = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return "cart id: %s" %(self.id)


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, null=True, blank=True, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.IntegerField(default=1)
    total_for_product = models.DecimalField(default=100.00, decimal_places=2, max_digits=10000)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        try:
            return str(self.cart.id)
        except:
            return self.product.title

zappy-branch-order-history/mainapp/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    location = models.CharField(max_length=255, blank=True)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Product(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False)
    description = models.TextField( null=True, blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=100, default=2999.99)
    slug = models.SlugField(unique=True)
    product_image = models.FileField(upload_to='product_image/', default='')
    # category = models.CharField(max_length=200, default='Vegetables')
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)


    def __str__(self):
        return self.title + ' - ' + self.description

    class Meta:
        unique_together = ('title', 'slug')

zappy-branch-order-history/mainapp/forms.py
from django import forms
from .models import Profile,User

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('location',)

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

zappy-branch-order-history/carts/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse
# from django.core.urlresolvers import reverse

# Create your views here.
from .models import Cart, CartItem
from mainapp.models import Product

def view(request):
    try:
        the_id = request.session['cart_id']
    except:
        the_id = None

    if the_id:
        cart = Cart.objects.get(id=the_id)
        context = {"cart": cart}
    else:
        context = {"empty": True, "msg": "Your cart is Empty"}
    return render(request, "carts/view.html", context)


def update_cart(request, slug):
    request.session.set_expiry(1800)
    try:
        qty = request.GET.get('qty')
        update_qty = True
    except:
        qty = None
        update_qty = False

    try:
        the_id = request.session['cart_id']
    except:
        new_cart = Cart()
        new_cart.save()
        request.session['cart_id'] = new_cart.id
        the_id = new_cart.id

    cart = Cart.objects.get(id=the_id)

    try:
        product = Product.objects.get(slug=slug)
    except Product.DoesNotExist:
        pass
    except:
        pass

    cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)

    if created:
        print("created")

    if update_qty and qty:
        if int(qty) == 0:
            cart_item.delete()
        else:
            cart_item.quantity = qty
            cart_item.save()
    else:
        pass

    # if not cart_item in cart.items.all():
    #     cart.items.add(cart_item)
    # else:
    #     cart.items.remove(cart_item)

    new_total = 0.00
    for item in cart.cartitem_set.all():
        total_for_product = float(item.product.price) * item.quantity
        new_total += total_for_product

    request.session['items_total'] = cart.cartitem_set.count()
    cart.total = new_total
    cart.save()
    return HttpResponseRedirect(reverse("carts:cart"))

zappy-branch-order-history/mainapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Q
from .models import Product
from django.contrib.auth.decorators import login_required
from .forms import ProfileForm, UserForm
from django.contrib.auth import logout
from django.http import HttpResponseRedirect

def index(request):
    product = Product.objects.all()
    context = {"products":product}
    return render(request, 'mainapp/index.html', context)

def signin(request):
    return render(request, 'registration/login.html', context)

def logoutView(request):
    logout(request)
    return HttpResponseRedirect("/")

# sign up user if they are not registered
def signup(request):
    form = UserCreationForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('/')
    context = { "form" : form }
    return render(request, 'registration/signup.html', context)

# def cart(request):
#     context = { 'title': 'Cart'}
#     return render(request, 'mainapp/cart.html', context)

def detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    context = {"product":product}
    return render(request, 'mainapp/detail.html', context)

def search(request):
    query = request.GET['q']
    if query:
        product = Product.objects.filter(Q(title__icontains=query))
        context = {
            'title': 'Search Results',
            'products': product
        }
        return render(request, 'mainapp/search.html', context)
    else:
        product = Product.objects.all()
        context = {"products":product}
        return render(request, 'mainapp/index.html', context)

@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('/')
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'mainapp/profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

zappy-branch-order-history/mainapp/templates/mainapp/cart.html
{% extends 'mainapp/layout.html' %}
{% load static %}

{% block content %}

<h1>{{title}}</h1>

{% endblock %}

zappy-branch-order-history/mainapp/templates/mainapp/detail.html
{% extends 'mainapp/layout.html' %}
{% load static %}

<div class="page-header">
  <h1>{{ product.title }}</h1>
</div>

{% block content %}
<div class="container content">


<div class="row">
  <div class="col-sm-4">
    <div class="col-xs-12 col-md-6">
      <img class="img-responsive content" src="{{product.product_image.url}}" alt="Card image cap">
    </div>
  </div>
  <div class="col-sm-8">
    <h1>{{ product.title }}
        <!-- <a href="{% url 'carts:update_cart' product.slug %}?qty=12" class="float-right">Add to Cart</a> -->
     </h1>
       <form class="form float-right" action="{% url 'carts:update_cart' product.slug %}" method="get">
         <input type="number" name="qty" value="1">
         <input type="submit" name="" value="Add To Cart">
       </form>
    <hr>
    price: {{product.price}} <br>
    Shipping: Free with 500+ Rs. purchase
    <hr>
    {{ product.description | linebreaks }}
  </div>
</div>


</div>

{% endblock %}

zappy-branch-order-history/mainapp/templates/mainapp/index.html
{% extends 'mainapp/layout.html' %}
{% load static %}

{% block content %}

<div class="container">

      <main role="main">

        <section class="jumbotron text-center">
          <div class="container">
            <h1 class="jumbotron-heading">Discover restaurants delivering to your doorstep</h1>
            <p class="lead text-muted">Place order on the zappy app</p>
            <!-- <p>
              <a href="#" class="btn btn-primary my-2">Main call to action</a>
              <a href="#" class="btn btn-secondary my-2">Secondary action</a>
            </p> -->
          </div>
        </section>

        <div class="album py-5 bg-light">
          <div class="container">
            <div class="row">
              {% for product in products %}
              <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                  <img class="card-img-top" src="{{product.product_image.url}}" alt="Card image cap">
                  <div class="card-body">
                    <h5><a href="{% url 'mainapp:detail' product.slug %}">{{ product.title }}</a></h5>
                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                    <label>price: {{ product.price }}</label>
                    <div class="d-flex justify-content-between align-items-center float-right">
                      <form class="form float-right" action="{% url 'carts:update_cart' product.slug %}" method="get">
                        <input type="number" name="qty" value="1">
                        <input type="submit" name="" value="Add To Cart">
                      </form>
                      <!-- <small class="text-muted">9 mins</small> -->
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>

      </main>
</div>
{% endblock %}

zappy-branch-order-history/mainapp/templates/mainapp/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Blog</title>

    <link rel="stylesheet" href="{% static 'mainapp/style.css' %}" type="text/css" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>
<body>

  <nav class="navbar-expand-lg navbar navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="container">
    <a class="navbar-brand" href="/">Zappy</a>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <form class="form-inline my-2 my-lg-0" action="/search/">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </ul>
      <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
        {% if not user.is_authenticated%}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'mainapp:signup'%}">Sign Up <span class="sr-only">(current)</span></a>
        </li>
        {% endif %}
        {% if user.is_authenticated%}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'orders:user_orders'%}"> Orders <span class="sr-only">(current)</span></a>
        </li>
        {% endif %}
        {% if user.is_authenticated%}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'mainapp:profile'%}">welcome, {{ user.username }} <span class="sr-only">(current)</span></a>
        </li>
        {% endif %}
        {% if user.is_authenticated%}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'mainapp:logout'%}">Logout<span class="sr-only">(current)</span></a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a href="{% url 'carts:cart'%}"><img class="nav-link float-left" src={% static 'mainapp/images/cart-3x.png' %}><span class="sr-only">(current)</span>{{ request.session.items_total }}</a>
        </li>
      </ul>
    </div>
  </div>
  </nav>


  {% block content %}
  {% endblock %}
  <br>
</body>

  <!-- <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Kartik Raghuwanshi 2018</p>
    </div>
  </footer> -->

</body>
</html>

zappy-branch-order-history/mainapp/templates/mainapp/profile.html
{% extends 'mainapp/layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
  <form method="post">
    {% csrf_token %}
    {{ user_form | crispy}}
    {{ profile_form | crispy }}
    <button class="btn btn-primary"type="submit">Save changes</button>
  </form>
</div>

{% endblock %}

zappy-branch-order-history/mainapp/templates/mainapp/search.html
{% extends 'mainapp/layout.html' %}
{% load staticfiles %}

{% block content %}

<div class="container">

     <div class="row">

       <!-- Product Entries Column -->
       <div class="col-md-8">

         <h1 class="my-4">{{title}}</h1>

         <!-- product list -->
         <div class="album py-5 bg-light">
           <div class="container">
             <div class="row">
               {% for product in products %}
               <div class="col-md-4">
                 <div class="card mb-4 box-shadow">
                   <img class="card-img-top" src="{{product.product_image.url}}" alt="Card image cap">
                   <div class="card-body">
                     <h5><a href="{% url 'mainapp:detail' product.slug %}">{{ product.title }}</a></h5>
                     <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                     <label>price: {{ product.price }}</label>
                     <div class="d-flex justify-content-between align-items-center">
                       <div class="btn-group">
                         <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                         <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                       </div>
                       <small class="text-muted">9 mins</small>
                     </div>
                   </div>
                 </div>
               </div>
               {% endfor %}
             </div>
           </div>
         </div>

         <!-- Pagination -->
         <!-- <div class="pagination">
           <span class="step-links">
               {% if posts.has_previous %}
                   <a href="?page=1">&laquo; first</a>
                   <a href="?page={{ contacts.previous_page_number }}">previous</a>
               {% endif %}
               <span class="current">
                   Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
               </span>
               {% if posts.has_next %}
                   <a href="?page={{ posts.next_page_number }}">next</a>
                   <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
               {% endif %}
           </span>
          </div> -->

       </div>
     </div>
   </div>
</div>
{% endblock %}