blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('addPost', views.addPost, name='addPost'),
    path('details/<int:id>', views.details, name='details'),
    path('<int:id>/update', views.update, name='update'),
    path('<int:id>/delete', views.delete, name='delete'),
    path('signup', views.signup, name='signup'),
    path('search', views.search, name='search'),
    path('category', views.category, name='category'),
]

blog/posts/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.
class Posts(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    category = models.CharField(max_length=200, default='Tutorials')
    fileUpload = models.FileField(upload_to='uploaded_image/', default='')
    author = models.ForeignKey(User, on_delete=models.CASCADE,default='')
    created_at = models.DateTimeField(default=datetime.now, blank=True)


    def __str__(self):
        return self.title + ' - ' + self.content

    class Meta:
        verbose_name_plural = "Posts"

blog/posts/forms.py
from django import forms
from .models import Posts

class PostForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = [
            "title",
            "content",
            "fileUpload",
        ]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'write some content here..'}),
        }

blog/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Posts
from posts.forms import PostForm
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Q
from django.utils import timezone
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

# Create your views here.
def index(request):
    posts = Posts.objects.all().order_by('-created_at')
    paginator = Paginator(posts, 3)

    page = request.GET.get('page')
    posts = paginator.get_page(page)
    context = {
        'title': 'Latest Posts',
        'posts': posts
    }
    return render(request, 'posts/index.html', context)

def signup(request):
    form = UserCreationForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('/')
    context = { "form" : form }
    return render(request, 'registration/signup.html', context)

def addPost(request):
    post = PostForm(request.POST or None, request.FILES)
    if post.is_valid():
        p = post.save(commit=False)
        p.author = request.user
        p.category = request.POST.get('category')
        p.save()
        return redirect("/")
    context = {"post":post}
    return render(request, 'posts/addPost.html', context)

def details(request, id):
    post = get_object_or_404(Posts, pk=id)
    context = {'post': post}
    return render(request, 'posts/details.html', context)

def update(request, id):
    if request.method == "POST":
        post = get_object_or_404(Posts, pk=id)
        postForm = PostForm(request.POST, request.FILES, instance=post)
        if postForm.is_valid():
            PF = postForm.save(commit=False)
            PF.created_at = timezone.now()
            PF.category = request.POST.get('category')
            PF.save()
            return redirect("/")
    if request.method == "GET":
        post = get_object_or_404(Posts, pk=id)
        postForm = PostForm(instance=post)
        context = {'post': postForm}
        return render(request, 'posts/update.html', context)

def delete(request, id):
    post = get_object_or_404(Posts, pk=id)
    post.delete()
    context = { 'msg': "deleted"}
    return redirect("/", context)

def search(request):
    query = request.GET['searchInput']
    if query:
        posts = Posts.objects.filter(Q(title__icontains=query))
        context = {
            'title': 'Search Results',
            'posts': posts
        }
    return render(request, 'posts/search.html', context)

def category(request):
    query = request.GET['category']
    if query:
        posts = Posts.objects.filter(Q(category__icontains=query))
        context = {
            'title': 'category',
            'posts': posts
        }
    return render(request, 'posts/search.html', context)

blog/posts/templates/posts/addPost.html
{% extends 'posts/layout.html' %}
{% load crispy_forms_tags %}

{% block content %}

<form enctype="multipart/form-data" method="post" action="" class="customform">
  <div class="form-group center content container">
    {{ post | crispy }}
    {% csrf_token %}
    <label for="">Category:</label>
    <select name="category">
      <option value="other">other</option>
      <option value="tech">tech</option>
      <option value="Tutorials">Tutorials</option>
      <option value="travel">travel</option>
    </select>
    <br>
    <input class="btn btn-primary" type="submit" name="" value="add post">
    <a class="btn btn-primary" href="/">Go back</a>
  </div>
</form>

{% endblock %}

blog/posts/templates/posts/details.html
{% extends 'posts/layout.html' %}
{% load static %}

{% block content %}

<!-- Page Header -->

    <header class="masthead" style="background-image: url('{{post.fileUpload.url}}')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto detailHead">
            <div class="post-heading">
              <h1>{{post.title}}</h1>
              <span class="meta"><p>Posted by
                <a href="#">{{ post.author }}</a>
                on {{post.created_at}}</p></span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Post Content -->
    <article>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto content">
            <p>{{post.content}}</p>
          </div>
        </div>
      </div>
    </article>

    <div class="container center">

    {% if user.is_authenticated %}
      <a class="btn btn-primary" href="/{{post.id}}/update" role="button">update</a>

      <a class="btn btn-primary" href="/{{post.id}}/delete" role="button">delete</a>
    {% endif %}
      <a class="btn btn-primary" href="/" role="button">Go back</a>

    </div>



{% endblock %}

blog/posts/templates/posts/index.html
{% extends 'posts/layout.html' %}
{% load staticfiles %}

{% block content %}

<div class="container">

     <div class="row">

       <!-- Blog Entries Column -->
       <div class="col-md-8">

         <h1 class="my-4">{{title}}</h1>

         <!-- Blog Post -->
         {% for post in posts %}
         <div class="card mb-4">
           {% if post.fileUpload %}
           <img class="card-img-top" src="{{post.fileUpload.url}}" alt="Card image cap">
           {% endif %}
           <div class="card-body">
             <h2 class="card-title">{{post.title}}</h2>
             <p class="card-text textlimit">{{post.content}}</p>
             <a href="details/{{post.id}}" class="btn btn-primary">Read More &rarr;</a>
           </div>
           <div class="card-footer text-muted">
             Posted on {{post.created_at}} by
             <a href="#">{{ post.author }}</a>
           </div>
         </div>
         {% endfor %}

         <!-- Pagination -->
         <div class="pagination">
           <span class="step-links">
               {% if posts.has_previous %}
                   <a href="?page=1">&laquo; first</a>
                   <a href="?page={{ contacts.previous_page_number }}">previous</a>
               {% endif %}

               <span class="current">
                   Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
               </span>

               {% if posts.has_next %}
                   <a href="?page={{ posts.next_page_number }}">next</a>
                   <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
               {% endif %}
           </span>
          </div>

        </div>

         <!-- Sidebar Widgets Column -->
       <div class="col-md-4">

         <!-- Search Widget -->
         <div class="card my-4">
           <h5 class="card-header">Search</h5>
           <div class="card-body">
             <div class="input-group">
               <form action="{% url 'posts:search' %}" method="get">
                 <input type="text" class="form-control" placeholder="Search for..." name="searchInput">
                 <span class="input-group-btn">
                   <input class="btn btn-secondary" type="submit" value="Go!">
                 </span>
               </form>
             </div>
           </div>
         </div>

         <!-- Categories Widget -->
         <div class="card my-4">
           <h5 class="card-header">Categories</h5>
           <div class="card-body">
             <div class="row">
               <div class="col-lg-6">
                <form action="{% url 'posts:category' %}" method="get">
                 <select name="category">
                    <option value="other">other</option>
                    <option value="tech">tech</option>
                    <option value="Tutorials">Tutorials</option>
                    <option value="travel">travel</option>
                 </select>
                 <input type="submit" name="" value="sumbit">
                </form>
               </div>
             </div>
           </div>
         </div>
       </div>
     </div>
   </div>
</div>
{% endblock %}

blog/posts/templates/posts/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Blog</title>

    <link rel="stylesheet" href="{% static 'posts/style.css' %}" type="text/css" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>
<body>

  <nav class="navbar-expand-lg navbar navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="container">
    <a class="navbar-brand" href="/">kBLog</a>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:addPost' %}">Add Post</a>
          </li>
        {% endif %}
        </ul>
        {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <h6 class="nav-link">welcome, {{ user.username }}</h6>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">logout</a>
          </li>
        </ul>
        {% else %}
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'posts:signup' %}">sign up</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">login</a>
            </li>
          </ul>
        {% endif %}
    </div>
  </div>
  </nav>


  {% block content %}
  {% endblock %}
  <br>
</body>

  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2018</p>
    </div>
  </footer>

</body>
</html>

blog/posts/templates/posts/search.html
{% extends 'posts/layout.html' %}
{% load staticfiles %}

{% block content %}

<div class="container">

     <div class="row">

       <!-- Blog Entries Column -->
       <div class="col-md-8">

         <h1 class="my-4">{{title}}</h1>

         <!-- Blog Post -->
         {% for post in posts %}
         <div class="card mb-4">
           {% if post.fileUpload %}
           <img class="card-img-top" src="{{ post.fileUpload.url}}" alt="Card image cap">
           {% endif %}
           <div class="card-body">
             <h2 class="card-title">{{post.title}}</h2>
             <p class="card-text textlimit">{{post.content}}</p>
             <a href="details/{{post.id}}" class="btn btn-primary">Read More &rarr;</a>
           </div>
           <div class="card-footer text-muted">
             Posted on {{post.created_at}} by
             <a href="#">{{ post.author }}</a>
           </div>
         </div>
         {% endfor %}

         <!-- Pagination -->
         <!-- <div class="pagination">
           <span class="step-links">
               {% if posts.has_previous %}
                   <a href="?page=1">&laquo; first</a>
                   <a href="?page={{ contacts.previous_page_number }}">previous</a>
               {% endif %}

               <span class="current">
                   Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
               </span>

               {% if posts.has_next %}
                   <a href="?page={{ posts.next_page_number }}">next</a>
                   <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
               {% endif %}
           </span>
          </div> -->

        </div>

         <!-- Sidebar Widgets Column -->
       <div class="col-md-4">

         <!-- Search Widget -->
         <div class="card my-4">
           <h5 class="card-header">Search</h5>
           <div class="card-body">
             <div class="input-group">
               <form action="{% url 'posts:search' %}" method="get">
                 <input type="text" class="form-control" placeholder="Search for..." name="searchInput">
                 <span class="input-group-btn">
                   <input class="btn btn-secondary" type="submit" value="Go!">
                 </span>
               </form>
             </div>
           </div>
         </div>

         <!-- Categories Widget -->
         <div class="card my-4">
           <h5 class="card-header">Categories</h5>
           <div class="card-body">
             <div class="row">
               <div class="col-lg-6">
                 <form action="{% url 'posts:category' %}" method="get">
                  <select name="category">
                     <option value="food">food</option>
                     <option value="tech">tech</option>
                     <option value="Tutorials">Tutorials</option>
                     <option value="travel">travel</option>
                  </select>
                  <input type="submit" name="" value="sumbit">
                 </form>
               </div>
             </div>
           </div>
         </div>
       </div>
     </div>
   </div>
</div>
{% endblock %}

blog/posts/templates/posts/update.html
{% extends 'posts/layout.html' %}

{% block content %}

<form enctype="multipart/form-data" method="post" action="" class="customform">
  <div class="form-group center container">
    {{ post.as_p }}
    {% csrf_token %}
    <label for="">Category:</label>
    <select name="category">
      <option value="other">other</option>
      <option value="tech">tech</option>
      <option value="Tutorials">Tutorials</option>
      <option value="travel">travel</option>
    </select>
    <br>
    <input class="btn btn-primary" type="submit" name="" value="update post">
    <a class="btn btn-primary" href="/posts">Go back</a>
  </div>
</form>

{% endblock %}